services:
  authtodo_api:
    build: ./docker/php
    command: [ "bash", "/app/docker/php/start.sh" ]
    container_name: authtodo_api
    volumes:
      - .:/app
    ports:
      - 80:80
    depends_on:
      authtodo_postgresql:
        condition: service_healthy
  authtodo_postgresql:
    image: postgres:17
    container_name: authtodo_postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: authtodo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - authtodo_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  authtodo_pgdata: